### ISSUE TITLE
Ability to change log flags

### ISSUE THREAD

**Issue by redecs** [savsgio/go-logger#2]
Hi! 

While the default `log.LstdFlags` are a good default option, I would like to be able to change the log flags and add `log.Llongfile` when troubleshooting. 
Do you think adding a `SetLogFlags` function similar to `SetOutput` would be useful? I'm willing to make a PR.

Also I would like to thank you for putting this together, I really felt the need for log levels in Go and this is a straight forward solution.

**Comment by savsgio** [comment]
Merged! Thanks! 😉

**Comment by redecs** [comment]
Awseome! Happy to help! Looking forward to seeing it tagged as a release to start using it! 😄  Thanks!

**Comment by savsgio** [comment]
@redecs 

Released [v2.1.0](https://github.com/savsgio/go-logger/releases/tag/v2.1.0) 🎉

**Comment by redecs** [comment]
Thanks @savsgio! 👍
