### ISSUE TITLE
Texts containing quotation marks ("), commas (,) are not escaped

### ISSUE THREAD

**Issue by joanasancho** [savsgio/go-logger#6]
The json encoder doesn't escape quotation marks ("), commas (,) and other values that need to be escaped. So, log messages containing those characters are wrong encoded.

Example:
`"foo": 'invalid param "bar"'`

Should be encoded as:
`"foo": "invalid param \"bar\""`

But it's encoded as:
`
"foo": "invalid param "bar""`

**Comment by savsgio** [comment]
Hi @joanasancho,

Fixed in release [v3.0.2](https://github.com/savsgio/go-logger/releases/tag/v3.0.2).

Thank you so much! 😉
